### ISSUE TITLE
Update to latest version of .NET

### ISSUE THREAD

**Issue by deadmeu** [flathub/org.freedesktop.Sdk.Extension.dotnet#18]
Please forgive my ignorance but I assume that this package should be tracking the latest version of .NET - is that correct? If so, could it be updated to provide the latest version (.NET 8)?

I understand the package `org.freedesktop.Sdk.Extension.dotnet8` exists, but installing the latest package every time a new .NET version is released seems like a hassle, and I assume that this version-less `org.freedesktop.Sdk.Extension.dotnet` package should simply point to the latest version.

**Comment by hfiguiere** [comment]
No. SDK versions are incompatible so it's important to have separate packages for separate versions. Also this one hasn't been updated in 3 years.
