### ISSUE TITLE
[FR] package PowerShell with dotnet runtime

### ISSUE THREAD

**Issue by ghost** [flathub/org.freedesktop.Sdk.Extension.dotnet#4]
Create a separate extension for this, requiring this extension to run. Or pack-in pwsh.

PowerShell is not Yet Another Shell, it's connected to dotnet and even allows interfacing with C# code compiled for .Net Core.

Also, PowerShell can be a nice add-in for VS Code and it's features.

**Comment by ghost** [comment]
You can close this issue if you don't like the idea.

The typical workaround can be using dotnet global tools

Like this:
`dotnet tool install --global PowerShell`

And add a path to `~/.dotnet/tools`

**Comment by refi64** [comment]
I'm not necessarily against it, but PowerShell would probably need some tweaks to work nicely in the Flatpak sandbox, and either way...it would probably have to be a separate extension. Packaging it here would mean that every app that needs dotnet to build would also be downloading PowerShell.
